In [1]:
import pandas as pd
import numpy as np

# #1.
- (5 Points) Write a Python/NumPy code block that finds the distinct/unique common items between these two arrays:
- a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
- b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
- Your output should contain only the distinct overlapping values. For example, if a 2 is found in both array a and array b,
- your output should contain only one 2 even if array a contains more than one 2 within it.

#### How to implement?
- 1) Using narray compare to get boolean array
- 2) Using boolean array to get values
- 3) Using numpy.unique() to get unique values

In [2]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

b_arr = (a == b) # get a boolean array
print(b_arr)

v_arr = a[b_arr] # get value through the boolean array
print(np.unique(v_arr)) # numpy.unique() can get unique values

[False  True False  True False  True False  True False False]
[2 4]


# #2
- Create the following 5x3 array using knowledge you have of Python’s / NumPy’s sequencing functionality
- so that you do not need to explicitly key in every integer value.
- 1 6 11
- 2 7 12
- 3 8 13
- 4 9 14
- 5 10 15

#### How to implement?
- 1) Using numpy.arange(start, end, steps) to generate a [1,....15] array
- 2) Using numpy.reshape(numbles of row, numbers of column) to reshape a 1D array to a 2D array
- 3) Using .T to transform axis0 * axis1 to axis1*axis0

In [3]:
a = np.arange(1, 16, 1).reshape(3, 5)
a.T

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

# #3
- You are given the following two arrays:
- a = np.array([12, 5, 7, 15, 3, 1, 8])
- b = np.array([14, 6, 3, 11, 19, 12, 5])
- Write a Python/Numpy code block that removes from array a any items that are also present in array b

#### How to implement?
- 1) Using numpy.isin(arr1, arr2) to get a boolean array of the same shape as element that is True where an element of element is in test_elements and False otherwise.
- 2) Using ~ to get a negtive boolean arry
- 3) Using the negtive boolean arry to get values

In [4]:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])

In [5]:
boolean_arr =np.isin(a, b)

In [6]:
b[~boolean_arr]

array([ 3, 11, 12,  5])

# #4
Suppose you have ridden a bicycle from New York City to Key West, Florida. Your bicycle odometer shows
the total miles you have travelled thus far, which you make a note of each day with paper and pencil. Your first two
entries might be ‘55’ and ‘120’, indicating that you rode your bike 55 miles on day 1 and 65 miles on day 2. Your task is
to create a NumPy array wherein you can record the cumulative miles you recorded each day during your trip “by hand”.
Then use your Python skills to show the total miles that you rode each day. Assume the trip took a total of 35 days and
included at least 4 non-consecutive days where no cycling was possible due to either weather conditions or personal
fatigue/soreness. For the remaining 31 days, you would have covered the entire distance between NYC and Key West.
Complete your work within your Jupyter Notebook for this assignment and be sure to include a writeup explaining your
approach to this problem, including the ways in which you decided to make use of NumPy.

- From New York City to Key West: 1519 mi

#### How to implement?
##### Q4 Method 1
- 1) get array from the 0th value to the 34th value. Length is 34.
- 2) get array from the 1st value to the 35th value. Length is 34.
- 3) get the frist value
- 4) Using '-' of mathmatics of array to get differents of two array
- 5) Using numpy.append(arr1, arr2) to combine two array

In [7]:
a = np.array([55, 120, 120, 145, 155, 200, 200, 
              265, 280, 320, 380, 411, 466, 503, 
              547, 547, 600, 640, 689, 723, 781,
             825, 860, 910, 910, 999, 999, 1061,
             1137, 1201, 1299, 1370, 1450, 1519])
pre_a = a[0:33].copy()
last_a = a[1:].copy()
frist = a[0]
daily_a = last_a - pre_a
daily_a
all_daily_a = np.append(frist, daily_a)
all_daily_a

array([55, 65,  0, 25, 10, 45,  0, 65, 15, 40, 60, 31, 55, 37, 44,  0, 53,
       40, 49, 34, 58, 44, 35, 50,  0, 89,  0, 62, 76, 64, 98, 71, 80, 69])

##### Q4 Method 2
- 1) Using numpy.diff(arr) to get different value.
- 2) Using numpy.append(arr1, arr2) to combine the frist value array and the diff array(34 items)

##### diff
- https://numpy.org/doc/stable/reference/generated/numpy.diff.html



In [8]:
# Method 2
diff_arr = np.diff(a)
all_daily_a = np.append(a[0], diff_arr)
all_daily_a

array([55, 65,  0, 25, 10, 45,  0, 65, 15, 40, 60, 31, 55, 37, 44,  0, 53,
       40, 49, 34, 58, 44, 35, 50,  0, 89,  0, 62, 76, 64, 98, 71, 80, 69])

#### Q4 Method 3

- 1) Using lambda and map to calculate different value
- 2) sing numpy.append(arr1, arr2) to combine the frist value array and the diff array(34 items)

```python
items = [1, 2, 3, 4, 5]
squared = list(map(lambda x, y: y - x, items[:3], items[1:4]))
squared
```

In [9]:
a
diff_arr = list(map(lambda x, y : (y - x), a[:33], a[1:34]))
all_daily_a = np.append(a[0], diff_arr)
all_daily_a


array([55, 65,  0, 25, 10, 45,  0, 65, 15, 40, 60, 31, 55, 37, 44,  0, 53,
       40, 49, 34, 58, 44, 35, 50,  0, 89,  0, 62, 76, 64, 98, 71, 80, 69])

# #5 ndarray

In [10]:
# supress scientific notation
np.set_printoptions(suppress = True)

# read the data file from GitHub and convert to a NumPy ndarray object
nyc_water_df = pd.read_csv('https://raw.githubusercontent.com/jtopor/DAV-5400/master/Week4/Water_Consumption_In_The_New_York_City.csv')
nyc_water = nyc_water_df.values

# verify you have an ndarray object
type(nyc_water)

numpy.ndarray

In [11]:
nyc_water_df.head(5)

Year  New York City Population  NYC Consumption(Million gallons per day)  \
0  1979                 7102100.0                                    1512.0   
1  1980                 7071639.0                                    1506.0   
2  1981                 7089241.0                                    1309.0   
3  1982                 7109105.0                                    1382.0   
4  1983                 7181224.0                                    1424.0   

   Per Capita(Gallons per person per day)  
0                                     213  
1                                     213  
2                                     185  
3                                     194  
4                                     198

In [12]:
# print nyc_water shape
nyc_water.shape

(39, 4)

In [13]:
# What is the maximum yearly NYC consumption of water in millions of gallons per day?

# to get the 3rd column. It is NYC Consumption(Million gallons per day)
nyc_consumptions = nyc_water[:, 2]

print("Max value of NYC Consumption(Million gallons per day) is %.2f" %np.max(nyc_consumptions))

Max value of NYC Consumption(Million gallons per day) is 1512.00


In [14]:
# How many calendar years are represented within this data set?

# to get the 1st column. It is Year
nyc_years = nyc_consumptions = nyc_water[:, 0]

print("%d calendar years" %len(np.unique(nyc_years)))

39 calendar years


In [15]:
# What is the mean and the standard deviation of the per capita daily water consumption?

# to get the 4th column. It is Per Capita(Gallons per person per day)
nyc_daily_consumptions = nyc_consumptions = nyc_water[:, 3]

print("the mean is %.2f" %nyc_daily_consumptions.mean())

print("the standard deviation is %.2f" %nyc_daily_consumptions.std())

the mean is 160.31
the standard deviation is 31.52


In [16]:
# What is the increase or decrease in population from year to year?

# to get the 2nd column. It is New York City Population
populations = nyc_water[:, 1]
pop_diff = np.diff(populations)
print(pop_diff)

[-30461.   17602.   19864.   72119.   53290.   39540.   45192.   23230.
  11243.   -9544.   -8525.   38851.   54443.   77222.   64292.   62582.
  64772.   75631.   84816.   89401.   60618.   16685.5  16685.5  16685.5
  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5 108965.
  77081.   61281.   49530.   44512.   21171.   85025. ]


# #5 pandas

In [17]:
# supress scientific notation
np.set_printoptions(suppress = True)

# read the data file from GitHub and convert to a NumPy ndarray object
nyc_water = pd.read_csv('https://raw.githubusercontent.com/jtopor/DAV-5400/master/Week4/Water_Consumption_In_The_New_York_City.csv')

# verify you have an ndarray object
type(nyc_water)

# print the head 5 rows
nyc_water.head(5)

Year  New York City Population  NYC Consumption(Million gallons per day)  \
0  1979                 7102100.0                                    1512.0   
1  1980                 7071639.0                                    1506.0   
2  1981                 7089241.0                                    1309.0   
3  1982                 7109105.0                                    1382.0   
4  1983                 7181224.0                                    1424.0   

   Per Capita(Gallons per person per day)  
0                                     213  
1                                     213  
2                                     185  
3                                     194  
4                                     198

In [18]:
# calculate this data's basic statistic information.
nyc_water.describe()

Year  New York City Population  \
count    39.000000              3.900000e+01   
mean   1998.000000              7.789046e+06   
std      11.401754              4.770796e+05   
min    1979.000000              7.071639e+06   
25%    1988.500000              7.343326e+06   
50%    1998.000000              7.858259e+06   
75%    2007.500000              8.133419e+06   
max    2017.000000              8.622698e+06   

       NYC Consumption(Million gallons per day)  \
count                                 39.000000   
mean                                1234.207692   
std                                  174.721588   
min                                  990.200000   
25%                                 1081.350000   
50%                                 1237.200000   
75%                                 1375.500000   
max                                 1512.000000   

       Per Capita(Gallons per person per day)  
count                               39.000000  
mean                               160.307692  
std                                 31.930973  
min                                115.000000  
25%                                133.500000  
50%                                155.000000  
75%                                188.000000  
max                                213.000000

In [19]:
# What is the maximum yearly NYC consumption of water in millions of gallons per day?
col_names = nyc_water.columns # get column names
max_yearly_cow = nyc_water[col_names[2]].max() # get column 2 ('NYC Consumption(Million gallons per day)') and get max value of column 2
print("Max value of NYC Consumption(Million gallons per day) is %.2f" %max_yearly_cow)

Max value of NYC Consumption(Million gallons per day) is 1512.00


In [20]:
# How many calendar years are represented within this data set?
years = nyc_water[col_names[0]]

# print(years)

print("%d calendar years" %years.count())

39 calendar years


In [21]:
# What is the mean and the standard deviation of the per capita daily water consumption?
per_capitas = nyc_water[col_names[3]]
print("the mean is %.2f" %per_capitas.mean())
print("the standard deviation is %.2f" %per_capitas.std())

the mean is 160.31
the standard deviation is 31.93


In [22]:
# What is the increase or decrease in population from year to year?
populations = nyc_water[col_names[1]]
pop_diff = np.diff(populations)
print(pop_diff)

[-30461.   17602.   19864.   72119.   53290.   39540.   45192.   23230.
  11243.   -9544.   -8525.   38851.   54443.   77222.   64292.   62582.
  64772.   75631.   84816.   89401.   60618.   16685.5  16685.5  16685.5
  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5 108965.
  77081.   61281.   49530.   44512.   21171.   85025. ]
